### ISSUE TITLE
Better front page example in documentation?

### ISSUE THREAD

**Issue by legends2k** [unicode-rs/unicode-segmentation#70]
Both the [front page](https://crates.io/crates/unicode-segmentation) and [`unicode_segmentation::UnicodeSegmentation`'s example](https://unicode-rs.github.io/unicode-segmentation/unicode_segmentation/trait.UnicodeSegmentation.html#tymethod.graphemes) shows

```rust
let gr1 = UnicodeSegmentation::graphemes("a\u{310}e\u{301}o\u{308}\u{332}", true)
          .collect::<Vec<&str>>();
```

than the more elegant

```rust
let gr1 = "a\u{310}e\u{301}o\u{308}\u{332}".graphemes(true).collect::<Vec<&str>>();
```

**Comment by pedantic79** [comment]
Is this fixed by #76 ?

**Comment by legends2k** [comment]
@pedantic79 Nope, I still see the same example in [the front page](https://docs.rs/unicode-segmentation/*/unicode_segmentation/).

**Comment by pedantic79** [comment]
@legends2k I think that's because there wasn't been a new release since the PR was merged.
